version: '3'

volumes:
  pg_data:
  redis_data:
services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
#  redis:
#    image: redis:7-alpine
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/var/lib/redis/data
  backend:
    build: .
    env_file: .env
    depends_on:
      - db